image: ubuntu:bionic

pipelines:
  default:
    - step:
        script:
          # Dependencies
          - apt update
          - apt -y install cmake build-essential lcov curl mercurial git lsb-release wget
            libtinyxml-dev libxml2-utils ruby-dev libboost-dev g++-8
          - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave /usr/bin/g++ g++ /usr/bin/g++-8 --slave /usr/bin/gcov gcov /usr/bin/gcov-8
            python-psutil cppcheck
          # Static checking before building - fail fast
          - sh tools/code_check.sh
          - sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-latest.list'
          - wget http://packages.osrfoundation.org/gazebo.key -O - | apt-key add -
          - apt update
          - apt install -y
            libignition-math5-dev
            libignition-tools-dev
          # lcov
          - git clone https://github.com/linux-test-project/lcov.git
          - cd lcov
          - make install
          - cd ..
          # SDFormat
          - mkdir build
          - cd build
          - cmake .. -DCMAKE_BUILD_TYPE=coverage
          - make -j4
          - make test
          - make coverage
          - bash <(curl -s https://codecov.io/bash)
          - make install
          # Examples
          - cd ..
          - cd examples
          - mkdir build
          - cd build
          - cmake ..
          - make -j4
          - ./simple ../simple.sdf
